version: '3'

services:
  caseta_to_mqtt:
    image: caseta_to_mqtt_arm64:latest
    volumes:
      - "./etc-caseta-to-mqtt:/etc/caseta_to_mqtt"
    restart: unless-stopped
    environment:
      - "LOGLEVEL=DEBUG"
      - "ENV_FOR_DYNACONF=${EMV_FOR_DYNACONF?err}"
